### ISSUE TITLE
Not working for me on Rhythmbox 3.0.2, Ubuntu 14.04.

### ISSUE THREAD

**Issue by brianjcohen** [LukeCarrier/rhythmbox-rhythmsub#2]
I tried firing up Rhythmbox from the console I'm not seeing any useful console output.  I configured the server address, username, password and enabled the plugin. When I click on the Subsonic icon in the sidebar the little animated "sonar waves" start moving but the song library never loads. How might I go about starting to troubleshoot this?

**Comment by LukeCarrier** [comment]
Hi @brianjcohen 

I'm afraid that this plugin is incomplete and isn't likely to be completed until `gvfsd-http` is a little more stable. Please see #1. Sorry :(

**Comment by wngr** [comment]
Hi @LukeCarrier 

could you elaborate on the issue? I'd really like to see this plugin working with Rhythmbox.
Maybe there can be other another way?

Oliver

**Comment by LukeCarrier** [comment]
@wngr sure, I could have switched to using Twisted or something -- there are other libraries that provide the asynchronous I/O necessary to build something like this. It seemed silly at the time to introduce an entirely new dependency just to workaround a single bug in `gvfs`, but the developers evidently aren't interested in fixing this issue ;-)

I'm afraid I'm no longer interested in working on this plugin, though. I've sinced moved to using Emby and their web player is capable enough. If you'd like to take on maintenance of the plugin, you're welcome to fork it and I'll add a link to the `README` here.

**Comment by wngr** [comment]
Thanks for your answer. I'll look into it and will give you a shout.

**Comment by wngr** [comment]
@LukeCarrier 
I'm currently looking into the plugin. 
Quick question: The url gets saved with the uri rhythmsub://. [rhythmsub.py](../blob/master/rhythmsub.py), line 276.

gstreamer complains that there is no uri handler registered for that one. Am I missing something?

Thanks for your answer.

**Comment by LukeCarrier** [comment]
@wngr I'm not 100% sure I'm afraid.

I presume the reason I used a custom scheme in the URI would be handling authentication and maybe doing caching. Since I never successfully got my library synced because of the `gvfs` bug, I never gave playback much thought. Maybe [this plugin's source](https://github.com/lotan/rhythmbox-ampache) will help?

**Comment by wngr** [comment]
@LukeCarrier 
Aaah, I see. I was under the impression, that you had the basic functionality running. 

Thanks for your answer, I'll have a deeper look at it, also at the ampache plugin.
I'll give you a shout once I have something running ;).
